packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - spawn-sync

overrides:
  node-forge@<1.3.2: '>=1.3.2'

patchedDependencies:
  publish-browser-extension: patches/publish-browser-extension.patch
  wxt-module-safari-xcode: patches/wxt-module-safari-xcode.patch
